# MNIST

In [1]:
# Load MNIST dataset form keras
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [2]:
# Train data
print(train_images.shape)
print(len(train_labels))
print(train_labels[:10])
print(train_images.ndim)

(60000, 28, 28)
60000
[5 0 4 1 9 2 1 3 1 4]
3


In [3]:
# Test data
print(test_images.shape)
print(len(test_labels))
print(test_labels[:10])

(10000, 28, 28)
10000
[7 2 1 0 4 1 4 9 5 9]


In [4]:
# Build a neural network
import tensorflow
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [5]:
# Model compilation
model.compile(
    optimizer='rmsprop',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [6]:
# Initial data preparation
train_images = train_images.reshape((60_000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10_000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [7]:
# # Training the model
model.fit(
    x=train_images,
    y=train_labels,
    batch_size=128,
    epochs=5
)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.2625 - accuracy: 0.9256
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.1068 - accuracy: 0.9683
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0718 - accuracy: 0.9787
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0508 - accuracy: 0.9849
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0379 - accuracy: 0.9890


In [8]:
# Get predictions
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 105ms/step


array([2.3086773e-07, 6.3787065e-09, 9.2176087e-06, 2.5079621e-04,
       1.2976577e-11, 2.0124853e-07, 1.4960234e-12, 9.9973661e-01,
       6.1708299e-08, 2.9404437e-06], dtype=float32)

In [9]:
# Predicted number
result = predictions[0].argmax()
result

7

In [10]:
# Number's probability
result_probability = predictions[0][result]
result_probability

0.9997366

In [11]:
# Check predictions
result == test_labels[0]

True

In [12]:
# Evaluate model
test_loss, test_accuracy = model.evaluate(test_images, test_labels)
print(f'test accurace: {test_accuracy}')

313/313 [==============================] - 1s 3ms/step - loss: 0.0698 - accuracy: 0.9792
test accurace: 0.979200005531311


## Tensor is a container for data, usually numeric

In [15]:
# Scalar - zero rank tensor
import numpy as np
x = np.array(12)
x.ndim

0

In [16]:
# Vector - first rank tensor
x = np.array([12, 3, 6, 14, 7])
x.ndim

1

Don't confuse five-dimensional vector with five-dimensional tensors!

A five-dimensional vector has only one axis (and five values on that axis), while a five-dimensional tensor has five axes (and any number of values on each of them)

# page 62 (2nd ed.)