In [1]:
!pip install torch

In [2]:
import numpy as np
import torch

# Tensors

In [3]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
x = torch.Tensor(np.resize(np.arange(1, 13), (3, 4)))
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

# [numpy.resize](https://numpy.org/doc/stable/reference/generated/numpy.resize.html)

In [6]:
x.size()

torch.Size([3, 4])

In [7]:
x.shape

torch.Size([3, 4])

In [8]:
x[2, 1]

tensor(10.)

In [9]:
x[:, 2]

tensor([ 3.,  7., 11.])

In [10]:
x[2]

tensor([ 9., 10., 11., 12.])

In [11]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [12]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [13]:
np.random.seed(26)
y = torch.Tensor(np.resize(a=[np.random.randint(1, 12) for _ in range(12)], new_shape=(3, 4)))
y

tensor([[ 6.,  7.,  1.,  2.],
        [ 7.,  4., 11.,  1.],
        [ 5.,  3.,  2.,  8.]])

In [14]:
x + y

tensor([[ 7.,  9.,  4.,  6.],
        [12., 10., 18.,  9.],
        [14., 13., 13., 20.]])

In [15]:
x - y

tensor([[-5., -5.,  2.,  2.],
        [-2.,  2., -4.,  7.],
        [ 4.,  7.,  9.,  4.]])

In [16]:
x * y

tensor([[ 6., 14.,  3.,  8.],
        [35., 24., 77.,  8.],
        [45., 30., 22., 96.]])

In [17]:
x / y

tensor([[0.1667, 0.2857, 3.0000, 2.0000],
        [0.7143, 1.5000, 0.6364, 8.0000],
        [1.8000, 3.3333, 5.5000, 1.5000]])

In [18]:
x // y

tensor([[0., 0., 3., 2.],
        [0., 1., 0., 8.],
        [1., 3., 5., 1.]])

In [19]:
x % y

tensor([[1., 2., 0., 0.],
        [5., 2., 7., 0.],
        [4., 1., 1., 4.]])

In [20]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [21]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [22]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [23]:
# Mask
mask = x > 3
mask

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [24]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [25]:
x[x > 8]

tensor([ 9., 10., 11., 12.])

### Without .clone(), copy will be shadow, not deep

In [26]:
x.dtype

torch.float32

In [27]:
x = x.double()
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)

In [28]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [29]:
# From NumPy to PyTorch
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=torch.int32)

In [30]:
# From PyTorch to NumPy
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [31]:
# Create tensor with random numbers between 0 and zero
x = torch.rand(size=[2, 3])
x

tensor([[0.3649, 0.4731, 0.2642],
        [0.2200, 0.0199, 0.6673]])

In [32]:
# Check whether my laptop has GPU
torch.cuda.is_available()

False

In [33]:
# Switch into gpu (cuda)
torch.device('cuda:0')

device(type='cuda', index=0)

In [34]:
# Switch into cpu
# torch.device('cpu')

In [35]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

# Parallelism and acceleration are useful only in Big Data in short amount of data CPU is faster