In [1]:
import torch

In [2]:
x = torch.tensor(
    [[1., 2., 3., 4.],
     [5., 6., 7., 8.],
     [9., 10., 11., 12.]],
    requires_grad=True)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], requires_grad=True)

# [TORCH.TENSOR.REQUIRES_GRAD_](https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad_.html)

In [3]:
# Chech whether GPU is available
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [4]:
x = x.to(device)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], requires_grad=True)

# [TORCH.TENSOR.TO](https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad_.html)

In [5]:
function = 10 * (x ** 2).sum()
function.backward()
print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


# [TORCH.TENSOR.BACKWARD](https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html)

In [8]:
# Last and pre-last operations
print(function.grad_fn)
print(function.grad_fn.next_functions[0][0])